name: tests

on:
  push:

jobs:
  unittest:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Execute tests
        run: npm test
